language: r
warnings_are_errors: true
env: _R_CHECK_CRAN_INCOMING_=FALSE

r_binary_packages:
  - igraph
  - stringdist

r_github_packages:
  - jimhester/lintr

after_success:
  - Rscript -e 'lintr::lint_package()'

notifications:
  email:
    on_success: change
    on_failure: always
