language: r
cache: packages

r:
  - oldrel
  - release
  - devel

r_github_packages:
  - jimhester/lintr 
  - jimhester/covr

after_success:
  - Rscript tools/lint-and-covr.R

notifications:
  email: false

