language: r
cache: packages

r:
  - oldrel
  - release
  - devel

r_packages:
  - lintr
  - covr

after_success:
  - Rscript -e "lintr::lint_package()"
  - Rscript -e "library(covr); coveralls()"

notifications:
  email: false

