// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// scrm
List scrm(std::string args, std::string file);
RcppExport SEXP scrm_scrm(SEXP argsSEXP, SEXP fileSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::string >::type args(argsSEXP);
    Rcpp::traits::input_parameter< std::string >::type file(fileSEXP);
    __result = Rcpp::wrap(scrm(args, file));
    return __result;
END_RCPP
}
// test_RRG_sample
double test_RRG_sample();
RcppExport SEXP scrm_test_RRG_sample() {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    __result = Rcpp::wrap(test_RRG_sample());
    return __result;
END_RCPP
}
// test_RRG_sampleUnitExpo
double test_RRG_sampleUnitExpo();
RcppExport SEXP scrm_test_RRG_sampleUnitExpo() {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    __result = Rcpp::wrap(test_RRG_sampleUnitExpo());
    return __result;
END_RCPP
}
// test_RRG_sampleExpoExpoLimit
double test_RRG_sampleExpoExpoLimit(double lambda, double b, double limit);
RcppExport SEXP scrm_test_RRG_sampleExpoExpoLimit(SEXP lambdaSEXP, SEXP bSEXP, SEXP limitSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    Rcpp::traits::input_parameter< double >::type limit(limitSEXP);
    __result = Rcpp::wrap(test_RRG_sampleExpoExpoLimit(lambda, b, limit));
    return __result;
END_RCPP
}
