# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Simulate the evolution of biological sequences
#' 
#' @section Seeding:
#' The R version of scrm uses random number generated by R's random generator. 
#' Therefore, its '-seed' argument of the command line version will be ignored, 
#' and no seed is given in the output. 
#' Use the R function \code{\link{set.seed}} prior to calling this 
#' function to ensure reproduciblity of results.
#' 
#' @param args A string containing the command line arguments for scrm. Look at
#'             scrms vignette for a description of available arguments.
#' @param file If provided, scrm will additionally write it is output into 
#'             a file with the given file, using an ms-like text output.
#' @return A named list of summary statistics. 
#' @export
#' @examples
#' # 5 Chromosomes with 100 bases each with recombination and mutation
#' sum_stats <- scrm('5 1 -r 5 100 -t 5 -T -L')
#' str(sum_stats)
#'
#' # Simulate the site frequency spectrum at 3 loci. For each locus 
#' # 10 Chromosomes of 1Mb length are sampled from two populations with 
#' # migration inbetween.
#' scrm('10 3 -r 400 1000000 -l 100000 -I 2 4 6 0.5 -t 300 -oSFS')$sfs
scrm <- function(args, file = "") {
    .Call('scrm_scrm', PACKAGE = 'scrm', args, file)
}

test_RRG_sample <- function() {
    .Call('scrm_test_RRG_sample', PACKAGE = 'scrm')
}

test_RRG_sampleUnitExpo <- function() {
    .Call('scrm_test_RRG_sampleUnitExpo', PACKAGE = 'scrm')
}

test_RRG_sampleExpoExpoLimit <- function(lambda, b, limit) {
    .Call('scrm_test_RRG_sampleExpoExpoLimit', PACKAGE = 'scrm', lambda, b, limit)
}

