# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Simulation the evolution of biological sequences
#' 
#' @section Seeding:
#' The R version of scrm uses random number generated by R's random generator. 
#' Therefore, its '-seed' argument will be ignored, and no seed is given in its
#' output. Use the R function \code{\link{set.seed}} prior to calling this 
#' function to ensure reproduciblity of results.
#' 
#' @param args A string containing the command line arguments for scrm. Look at
#'             scrms vignette for a description of available arguments.
#' @param file File provided, scrm will additionally write it is output into 
#'             the given file, using an ms-like text format.
#' @export
#' @examples
#' set.seed(17)
#' scrm('5 1 -r 10 100 -t 5')
#' \dontrun{scrm('5 1 -r 10 100 -t 5', file = tempfile('scrm_'))}
scrm <- function(args, file = "") {
    .Call('scrm_scrm', PACKAGE = 'scrm', args, file)
}

test_RRG_sample <- function() {
    .Call('scrm_test_RRG_sample', PACKAGE = 'scrm')
}

test_RRG_sampleUnitExpo <- function() {
    .Call('scrm_test_RRG_sampleUnitExpo', PACKAGE = 'scrm')
}

test_RRG_sampleExpoExpoLimit <- function(lambda, b, limit) {
    .Call('scrm_test_RRG_sampleExpoExpoLimit', PACKAGE = 'scrm', lambda, b, limit)
}

